//! DNS (P5d, MVP): generate a `resolv.conf` from the host's upstream resolvers to
//! drop into a container, so names resolve. The systemd-resolved stub
//! (`127.0.0.53`) is filtered out — a container can't reach the host's loopback —
//! falling back to public resolvers. An embedded name-resolving responder (so
//! containers resolve each other by name) is the P5h target.

use std::path::Path;

use crate::error::{Error, Result};

/// The host's usable upstream nameservers (loopback stubs filtered), or a public
/// fallback if none are found.
pub fn host_upstreams() -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for src in ["/run/systemd/resolve/resolv.conf", "/etc/resolv.conf"] {
        let Ok(text) = std::fs::read_to_string(src) else {
            continue;
        };
        for line in text.lines() {
            if let Some(ns) = line.trim().strip_prefix("nameserver ") {
                let ns = ns.trim().to_string();
                if !ns.starts_with("127.") && ns != "::1" && !out.contains(&ns) {
                    out.push(ns);
                }
            }
        }
        if !out.is_empty() {
            break;
        }
    }
    if out.is_empty() {
        out = vec!["1.1.1.1".to_string(), "8.8.8.8".to_string()];
    }
    out
}

/// Render `resolv.conf` text for the given upstreams.
pub fn render_resolv_conf(upstreams: &[String]) -> String {
    let mut s = String::from("# generated by dn7-container\n");
    for ns in upstreams {
        s.push_str("nameserver ");
        s.push_str(ns);
        s.push('\n');
    }
    s
}

/// Write `resolv.conf` into a container's `/etc` (e.g. the overlay upper's `etc`),
/// creating the directory if needed. Uses the host's upstream resolvers.
pub fn write_resolv_conf(etc_dir: &Path) -> Result<()> {
    write_resolv_conf_with(etc_dir, &host_upstreams())
}

/// Like [`write_resolv_conf`] but with explicit nameservers (the container's
/// requested DNS); falls back to the host upstreams when `servers` is empty.
pub fn write_resolv_conf_with(etc_dir: &Path, servers: &[String]) -> Result<()> {
    std::fs::create_dir_all(etc_dir).map_err(Error::io(etc_dir))?;
    let upstreams: Vec<String> = if servers.is_empty() {
        host_upstreams()
    } else {
        servers.to_vec()
    };
    let content = render_resolv_conf(&upstreams);
    let p = etc_dir.join("resolv.conf");
    std::fs::write(&p, content).map_err(Error::io(&p))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_lists_each_nameserver() {
        let s = render_resolv_conf(&["1.1.1.1".into(), "8.8.8.8".into()]);
        assert!(s.contains("nameserver 1.1.1.1\n"));
        assert!(s.contains("nameserver 8.8.8.8\n"));
    }

    #[test]
    fn host_upstreams_never_empty_and_no_loopback() {
        let up = host_upstreams();
        assert!(!up.is_empty());
        assert!(!up.iter().any(|n| n.starts_with("127.") || n == "::1"));
    }
}
